name: appfigurateflutter
description: Appfigurate SDK flutter plugin
version: 3.1.3
homepage: https://www.electricbolt.co.nz

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: nz.co.electricbolt.appfigurateflutter
        pluginClass: AppfigurateFlutterPlugin
      ios:
        pluginClass: AppfigurateFlutterPlugin
