name: appfigurateflutter
description: Appfigurate SDK flutter plugin for iOS mobile apps.
version: 5.0.0
homepage: https://www.electricbolt.co.nz

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AppfigurateFlutterPlugin
